server:
  port: 9002
spring:
  cloud:
    stream:
      kafka:
        binder:
          headers: x-retries
        streams:
          binder:
            application-id: stream-processor
            brokers:
            - localhost:9092
      bindings:
        output:
          destination: Producer
          content-type:
            application/json
        input:
          destination: dead-letter-topic
          content-type:
            application/json
        failedMessage:
          content-type:
            application/json
            