server:
  port: 9001
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: Producer
          content-type:
            application/json
      kafka:
        binder:
          brokers: localhost:9092
